import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
//import Section from "./component/Section";
import { Header } from "./component/Header"; 
import Footer from "./component/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Renergent app",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico' 
  }
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div>
          <div>
            <Header/>
            {/* <Footer/> */}
            {}
            {/* <Section /> */}
          </div>
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
