import "./globals.css";
import LayoutWrapper from "./component/LayoutWrapper";

export const metadata = {
  title: "Renergent app",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <LayoutWrapper>{children}</LayoutWrapper>
      </body>
    </html>
  );
}